geo $http_x_forwarded_for $ru {
    default 0;
    include /etc/nginx/ru_ips.conf;
    
    172.16.0.0/12 1;
}

server {
    listen 80;

    location = /stop {
        default_type text/html;
        return 403 '<h1 style="color:red; text-align:center; margin-top:20%">ACCESS RESTRICTED</h1>';
    }

    location / {
        if ($ru) {
            return 302 /stop;
        }
        
        proxy_pass http://app:7777;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}